import Header from './components/Header'
import { Roboto } from 'next/font/google';
import './styles/index.css'

const roboto = Roboto({
  variable: '--font-roboto',
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap'
});

export const metadata = {
  title: 'PrettyUgly',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${roboto.variable}`}>
      <body>
        <Header />
        {children}
        <div id='portal' />
      </body>
    </html>
  )
}
